# Environment settings
USER_ID_FIELD: uid
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [uid, item_id, timestamp]
    item: [item_id, venue_category_name, lat, lon]

save_dataset: False
save_dataloaders: False

field_separator: ','
benchmark_filename: ['part1', 'part2', 'part3']

seed: 1234
reproducibility: True


# Evaluation config
metrics: ['Hit', 'Precision']
valid_metric: Hit@10
metric_decimal_place: 4

eval_args: {
            group_by: 'user',
            order: 'TO', # temporal order
            split: {'LS': 'valid_and_test'}, # leave one out
            mode: 'full'
            }
